Dakota - Fix CommonsController delete bug
ucsb-cs156-s24/proj-happycows-s24-4pm-6 pull request #25
Opened 2024-05-21 21:54 UTC by dakotazoid56

## Overview

In this PR, (insert a brief description of what this PR enables for the end user as well as coders. If this placeholder text is still in place, this PR is not yet ready for review).

## Screenshots (Optional)

![Generic placeholder image](https://picsum.photos/640/480)

## Feedback Request (Optional)

Please give suggestions on the following:
- This method might not be the best way to do things. What do you think?
- The way this is implemented is the best I can think of. Is it acceptable?
- Where should these things go? I put them here, but it feels out of place.

## Future Possibilities (Optional)

Some possible points could be:
- This is the beginning/part of (insert feature).
- We can extend this to add (something beyond current functions).
- This can make things easier to (insert project).

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #0

2024-05-21 23:08 UTC, nbelle1 submitted a review, later dismissed
LGTM

2024-05-22 23:47 UTC, sangitakunapuli requested changes
Looks good, please remove the unnecessary comment

2024-05-22 23:47 UTC, sangitakunapuli commented on src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java
> +    void deleteByUserCommons(UserCommons userCommons); // Add this line
Please remove this comment

2024-05-24 22:23 UTC, pconrad approved these changes
LGTM!

2024-05-24 22:24 UTC, merged